### ISSUE TITLE
Support for react 15.0.0-rc1

### ISSUE THREAD

**Issue by RobinBressan** [bkonkle/jsx-chai#4]
Hi,

Since react has switched to strict semver, the peer dependency prevents from migrating to React 15.0.0.

Could you release a new version with this use case?

Thank you

**Comment by bkonkle** [comment]
Thanks for letting me know! I'll get a new version out as soon as I have a
chance. :+1:

**Comment by rgbkrk** [comment]
Looking forward to this, so I'll submit a PR now that the official is out. Any idea if/how you would want to straddle releases?

**Comment by jharris4** [comment]
+1 on React 15 support.

**Comment by bkonkle** [comment]
Thanks to @rgbkrk for the pull request!
