### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by biehlio** [bkonkle/jsx-chai#5]
Any plans on creating TypeScript Definitions?

typings search jsx-chai --ambient
No results found for search

**Comment by biehlio** [comment]
we don't plan on using this anymore...

**Comment by bkonkle** [comment]
Sorry I wasn't able to respond to this sooner. I've actually transitioned to using `enzyme`, so I totally understand your decision to move to something else. ;-) Have a great weekend!
